server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signerKey: "+tCUyqjsrZOg9b5ChVCb2+OGPMJQe4zI+rJSACpZ4vK/FXrD5wEND4gXQa7jxWhJ"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds



